language: java
dist: trusty
jdk:
 - openjdk8
 - openjdk9
 - openjdk10
 - openjdk11
 - openjdk12
 - openjdk13
 - openjdk14
script: mvn clean install --batch-mode
matrix:
    - jdk: openjdk8
branches:
  only:
    - master
after_success:
  - mvn jacoco:report coveralls:report
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#openmrs"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    use_notice: true
    skip_join: true
sudo: false
